=== PascualDaniel/SEW/practica2/Ejercicio-1/Tarea-4/arbol.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/arbol" elementFormDefault="qualified" targetNamespace="http://tempuri.org/arbol" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="arbol">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="persona" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="apellidos" />
        <xs:element ref="datosNacimiento" />
        <xs:element minOccurs="0" maxOccurs="1" ref="datosFallecimiento" />
        <xs:element ref="fotografias" />
        <xs:element minOccurs="0" maxOccurs="1" ref="videos" />
        <xs:element ref="comentarios" />
        <xs:element minOccurs="0" maxOccurs="1" ref="padres" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="padres">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="persona" />
        <xs:element ref="persona" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="apellidos" type="xs:string" />
  <xs:element name="datosNacimiento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fechaNacimiento" />
        <xs:element ref="lugarNacimiento" />
        <xs:element ref="coordenadasNacimiento" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaNacimiento" type="xs:string" />
  <xs:element name="lugarNacimiento" type="xs:string" />
  <xs:element name="coordenadasNacimiento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datosFallecimiento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fechaFallecimiento" />
        <xs:element ref="lugarFallecimiento" />
        <xs:element ref="coordenadasFallecimiento" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaFallecimiento" type="xs:string" />
  <xs:element name="lugarFallecimiento" type="xs:string" />
  <xs:element name="coordenadasFallecimiento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitud" type="xs:string" />
  <xs:element name="latitud" type="xs:string" />
  <xs:element name="altitud" type="xs:string" />
  <xs:element name="fotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:string" />
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video" type="xs:string" />
  <xs:element name="comentarios" type="xs:string" />
</xs:schema>

=== PascualDaniel/SEW/practica2/Ejercicio-2/Tarea-3/arbol.xml
<?xml version="1.0" encoding="UTF-8"?>

<arbol xmlns="http://www.uniovi.es/arbol"
xsi:schemaLocation="http://www.uniovi.es/arbol
arbol.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
	<persona>
		<nombre>Daniel</nombre>
		<apellidos>Pascual Lopez</apellidos>
		<datosNacimiento>
			<fechaNacimiento>2000-07-14</fechaNacimiento>
			<lugarNacimiento>Arriondas</lugarNacimiento>
			<coordenadasNacimiento>
				
				<longitud>   -5.1872</longitud>
				<latitud>	43.3849108 </latitud>
				<altitud>	40	</altitud>
			</coordenadasNacimiento>
			 
		</datosNacimiento>
		<fotografias>
			<foto>fotoMia.jpg</foto>
		</fotografias>
		<comentarios> Soy estudiante en EII OVIEDO</comentarios>
		
			<persona>
				<nombre>Dolores</nombre>
				<apellidos>Lopez Rigueira</apellidos>
				
				<datosNacimiento>
					<fechaNacimiento>1965-05-02</fechaNacimiento>
					<lugarNacimiento>Ferrol</lugarNacimiento>
					<coordenadasNacimiento>
						<longitud>    -8.22275 </longitud>
						<latitud>	 43.4883 </latitud>
						<altitud>	15	</altitud>
					</coordenadasNacimiento>
				</datosNacimiento>
				<fotografias>
					<foto>fotoMama.jpg</foto>
				</fotografias>
				<comentarios> Hace muy buenos frixuelos</comentarios>
				
					<persona>
						<nombre>Dolores</nombre>
						<apellidos>Rigueira Lagoa </apellidos>
						
						<datosNacimiento>
							<fechaNacimiento>1940-04-08</fechaNacimiento>
							<lugarNacimiento>Monforte</lugarNacimiento>
							<coordenadasNacimiento>
								<longitud>   -7.4942300 </longitud>
								<latitud>	42.5120100 </latitud>
								<altitud>	360 	</altitud>
							</coordenadasNacimiento>
						</datosNacimiento>
						<datosFallecimiento>
							<fechaFallecimiento>2001-09-03</fechaFallecimiento>
							<lugarFallecimiento>Ferrol</lugarFallecimiento>
							<coordenadasFallecimiento>
								<longitud>    -8.22275 </longitud>
								<latitud>	 43.4883 </latitud>
								<altitud>	15	</altitud>
							</coordenadasFallecimiento>
						</datosFallecimiento>
						<fotografias>
							<foto>fotodolo.jpg</foto>
						</fotografias>
						<comentarios> Tenia un 600</comentarios>
						
							<persona>
								<nombre>Manuel</nombre>
								<apellidos>Rigueira Fernandez </apellidos>
								
								<datosNacimiento>
									<fechaNacimiento>1910-10-18</fechaNacimiento>
									<lugarNacimiento>Ferrol</lugarNacimiento>
									<coordenadasNacimiento>
										<longitud>    -8.22275 </longitud>
										<latitud>	 43.4883 </latitud>
										<altitud>	15	</altitud>
									</coordenadasNacimiento>
								</datosNacimiento>
								<datosFallecimiento>
									<fechaFallecimiento>1986-10-08</fechaFallecimiento>
									<lugarFallecimiento>Ferrol</lugarFallecimiento>
									<coordenadasFallecimiento>
										<longitud>    -8.22275 </longitud>
										<latitud>	 43.4883 </latitud>
										<altitud>	15	</altitud>
									</coordenadasFallecimiento>
								</datosFallecimiento>
								<fotografias>
									<foto>fotomanuel.jpg</foto>
								</fotografias>
								<comentarios> Le gustaba pescar</comentarios>
								
							</persona>
							<persona>
								<nombre>Consolacion</nombre>
								<apellidos>Lagoa Suarez </apellidos>
								
								<datosNacimiento>
									<fechaNacimiento>1908-05-12</fechaNacimiento>
									<lugarNacimiento>Ferrol</lugarNacimiento>
									<coordenadasNacimiento>
										<longitud>    -8.22275 </longitud>
										<latitud>	 43.4883 </latitud>
										<altitud>	15	</altitud>
									</coordenadasNacimiento>
								</datosNacimiento>
								<datosFallecimiento>
									<fechaFallecimiento>1992-07-11</fechaFallecimiento>
									<lugarFallecimiento>Ferrol</lugarFallecimiento>
									<coordenadasFallecimiento>
										<longitud>    -8.22275 </longitud>
										<latitud>	 43.4883 </latitud>
										<altitud>	15	</altitud>
									</coordenadasFallecimiento>
								</datosFallecimiento>
								<fotografias>
									<foto>fotoConsolacion.jpg</foto>
								</fotografias>
								<comentarios> Era profesora</comentarios>
							
							</persona>
					
					</persona>
					<persona>
						<nombre>Daniel</nombre>
						<apellidos>Lopez Cao </apellidos>
					
						<datosNacimiento>
							<fechaNacimiento>1923-02-02</fechaNacimiento>
							<lugarNacimiento>Monforte</lugarNacimiento>
							<coordenadasNacimiento>
								<longitud>   -7.4942300 </longitud>
								<latitud>	42.5120100 </latitud>
								<altitud>	360 	</altitud>
							</coordenadasNacimiento>
						</datosNacimiento>
						<datosFallecimiento>
							<fechaFallecimiento>1975-01-13</fechaFallecimiento>
							<lugarFallecimiento>Ferrol</lugarFallecimiento>
							<coordenadasFallecimiento>
								<longitud>    -8.22275 </longitud>
								<latitud>	 43.4883 </latitud>
								<altitud>	15	</altitud>
							</coordenadasFallecimiento>
						</datosFallecimiento>
						<fotografias>
							<foto>fotoDaniCao.jpg</foto>
						</fotografias>
						<comentarios> Conducia un camion</comentarios>
					
							<persona>
								<nombre>Visitacion</nombre>
								<apellidos>Cao Somozas  </apellidos>
							
								<datosNacimiento>
									<fechaNacimiento>1900-01-03</fechaNacimiento>
									<lugarNacimiento>Monforte</lugarNacimiento>
									<coordenadasNacimiento>
										<longitud>   -7.4942300 </longitud>
										<latitud>	42.5120100 </latitud>
										<altitud>	360 	</altitud>
									</coordenadasNacimiento>
								</datosNacimiento>
								<datosFallecimiento>
									<fechaFallecimiento>1990-05-06</fechaFallecimiento>
									<lugarFallecimiento>Ferrol</lugarFallecimiento>
									<coordenadasFallecimiento>
										<longitud>    -8.22275 </longitud>
										<latitud>	 43.4883 </latitud>
										<altitud>	15	</altitud>
									</coordenadasFallecimiento>
								</datosFallecimiento>
								<fotografias>
									<foto>fotoVisitacion.jpg</foto>
								</fotografias>
								<comentarios> Tenia ojos azules</comentarios>
								
							</persona>
							<persona>
								<nombre>Pedro</nombre>
								<apellidos>Lopez Lopez </apellidos>
							
								<datosNacimiento>
									<fechaNacimiento>1897-09-02</fechaNacimiento>
									<lugarNacimiento>Monforte</lugarNacimiento>
									<coordenadasNacimiento>
										<longitud>   -7.4942300 </longitud>
										<latitud>	42.5120100 </latitud>
										<altitud>	360 	</altitud>
									</coordenadasNacimiento>
								</datosNacimiento>
								<datosFallecimiento>
									<fechaFallecimiento>1960-06-07</fechaFallecimiento>
									<lugarFallecimiento>Monforte</lugarFallecimiento>
									<coordenadasFallecimiento>
										<longitud>   -7.4942300 </longitud>
										<latitud>	42.5120100 </latitud>
										<altitud>	360 	</altitud>
									</coordenadasFallecimiento>
								</datosFallecimiento>
								<fotografias>
									<foto>fotoAbueloDani.jpg</foto>
								</fotografias>
								<comentarios> Fue policia</comentarios>
								
							</persona>
						
					</persona>
			
			</persona>
			<persona>
				<nombre>Jose Manuel</nombre>
				<apellidos>Pascual Vallina</apellidos>
			
				<datosNacimiento>
					<fechaNacimiento>1960-02-05</fechaNacimiento>
					<lugarNacimiento>Villanueva</lugarNacimiento>
					<coordenadasNacimiento>
						<longitud>  -5.150874 </longitud>
						<latitud>	43.36623576 </latitud>
						<altitud>	69	</altitud>
					</coordenadasNacimiento>
				</datosNacimiento>
				<fotografias>
					<foto>fotopas.jpg</foto>
				</fotografias>
				<comentarios> Le gusta el monte</comentarios>
			
					<persona>
						<nombre>Dolores</nombre>
						<apellidos>Vallina Trespando</apellidos>
					
						<datosNacimiento>
							<fechaNacimiento>1934-12-05</fechaNacimiento>
							<lugarNacimiento>Corao</lugarNacimiento>
							<coordenadasNacimiento>
								<longitud>  -5.06545 </longitud>
								<latitud>	43.34657731 </latitud>
								<altitud>	80	</altitud>
							</coordenadasNacimiento>
						</datosNacimiento>
						<datosFallecimiento>
							<fechaFallecimiento>1981-07-10</fechaFallecimiento>
							<lugarFallecimiento>Villanueva</lugarFallecimiento>
							<coordenadasFallecimiento>
								<longitud>  -5.150874 </longitud>
								<latitud>	43.36623576 </latitud>
								<altitud>	69	</altitud>
							</coordenadasFallecimiento>
						</datosFallecimiento>
						<fotografias>
							<foto>fotoAbuelaCorao.jpg</foto>
						</fotografias>
						<comentarios> Compro la primera tele del pueblo</comentarios>
				
							<persona>
								<nombre>Luz</nombre>
								<apellidos>Trespando Suarez </apellidos>
								
								<datosNacimiento>
									<fechaNacimiento>1903-01-01</fechaNacimiento>
									<lugarNacimiento>Corao</lugarNacimiento>
									<coordenadasNacimiento>
										<longitud>  -5.06545 </longitud>
										<latitud>	43.34657731 </latitud>
										<altitud>	80	</altitud>
									</coordenadasNacimiento>
								</datosNacimiento>
								<datosFallecimiento>
									<fechaFallecimiento>1950-11-01</fechaFallecimiento>
									<lugarFallecimiento>Corao</lugarFallecimiento>
									<coordenadasFallecimiento>
										<longitud>  -5.06545 </longitud>
										<latitud>	43.34657731 </latitud>
										<altitud>	80	</altitud>
									</coordenadasFallecimiento>
								</datosFallecimiento>
								<fotografias>
									<foto>fotoLuz.jpg</foto>
								</fotografias>
								<comentarios> Viajo mucho</comentarios>
							
							</persona>
							<persona>
								<nombre>Emiliano</nombre>
								<apellidos>Vallina Gomez</apellidos>
						
								<datosNacimiento>
									<fechaNacimiento>1908-02-02</fechaNacimiento>
									<lugarNacimiento>Oviedo</lugarNacimiento>
									<coordenadasNacimiento>
										<longitud>   -5.8555264 </longitud>
										<latitud>	43.3639746 </latitud>
										<altitud>	232 	</altitud>
									</coordenadasNacimiento>
								</datosNacimiento>
								<datosFallecimiento>
